### ISSUE TITLE
LOD_a_lot_v1.hdt does not work (java)

### ISSUE THREAD

**Issue by firmao** [wouterbeek/LOD-a-lot-www#1]
I just downloaded the hdt file from http://lod-a-lot.lod.labs.vu.nl/data/LOD_a_lot_v1.hdt
Reading the file the following error appears:

> 1936 [main] ERROR org.rdfhdt.hdtjena.bindings.BindingHDTNode  - get1(?o)
java.lang.NegativeArraySizeException
	at org.rdfhdt.hdtjena.cache.DictionaryCacheArray.put(DictionaryCacheArray.java:63)
	at org.rdfhdt.hdtjena.NodeDictionary.getNode(NodeDictionary.java:127)
	at org.rdfhdt.hdtjena.NodeDictionary.getNode(NodeDictionary.java:110)
	at org.rdfhdt.hdtjena.bindings.BindingHDTNode.get1(BindingHDTNode.java:115)
	at org.apache.jena.sparql.engine.binding.BindingBase.get(BindingBase.java:121)
	at org.rdfhdt.hdtjena.bindings.BindingHDTNode.format(BindingHDTNode.java:133)
	at org.apache.jena.sparql.engine.binding.BindingBase.format1(BindingBase.java:163)
	at org.apache.jena.sparql.engine.binding.BindingBase.toString(BindingBase.java:138)
	at org.apache.jena.sparql.core.ResultBinding.toString(ResultBinding.java:91)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at TestHDT.main(TestHDT.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
java.lang.NullPointerException
	at org.rdfhdt.hdtjena.bindings.BindingHDTNode.format(BindingHDTNode.java:135)
	at org.apache.jena.sparql.engine.binding.BindingBase.format1(BindingBase.java:163)
	at org.apache.jena.sparql.engine.binding.BindingBase.toString(BindingBase.java:138)
	at org.apache.jena.sparql.core.ResultBinding.toString(ResultBinding.java:91)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at TestHDT.main(TestHDT.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)

**Also the Jena Model.size() is a negative number.**

My code:

```
public class TestHDT {
	public static void main(String[] args) throws IOException {
		File file = new File("LOD_a_lot_v1.hdt");
		HDT hdt = null;
		try {
			hdt = HDTManager.mapHDT(file.getAbsolutePath(), null);
			HDTGraph graph = new HDTGraph(hdt);
			Model model = new ModelCom(graph);
			String sparql = "select * where {?s ?p ?o} limit 10";

			Query query = QueryFactory.create(sparql);

			QueryExecution qe = QueryExecutionFactory.create(query, model);
			ResultSet results = qe.execSelect();

			String csvName = "unidomains.csv";
			int count = 0;
			System.out.println("Model.size(): " + results.getResourceModel().size());
			while (results.hasNext()) {
				QuerySolution thisRow = results.next();
				System.out.println("Row " + (++count) + ": " + thisRow);
			}
			qe.close();
		} catch (Exception e) {
			e.printStackTrace();
		} finally {
			if (hdt != null) {
				hdt.close();
			}
		}
	}
}
```

**Comment by wouterbeek** [comment]
Are you using a version of HDT that has support for 64 bit integers?  LOD-a-lot surpasses the ~2B max. number that can be expressed by 32 bit integers.

**Comment by firmao** [comment]
how can I know if I'm using a version of HDT that has support for 64 bit integers?

**Comment by bjonnh** [comment]
@firmao One way would be to test for the return of TripleID().size()  it is 48 for the 64 bits version and 24 for the "normal" version.

**Comment by wouterbeek** [comment]
I closing this issue since 64 bit support was merged with the development branch a while ago.
